const Docker = require("dockerode");
const tarfs = require("tar-fs");
const path = require("path");
const os = require("os");
const fs = require("fs");
const util = require("util");
const net = require("net");
const { execFile } = require("child_process");
const { invalidate } = require("./containersCache");

const execFileAsync = util.promisify(execFile);

function dockerInstance() {
  return new Docker({ socketPath: process.env.DOCKER_SOCKET || '/var/run/docker.sock' });
}

function parseGitHubRepo(repoUrl) {
  try {
    const m = String(repoUrl).match(
      /^https?:\/\/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?$/i
    );
    if (!m) return null;
    return { owner: m[1], repo: m[2] };
  } catch {
    return null;
  }
}

async function getDefaultBranchFromGitHub(repoUrl) {
  const parsed = parseGitHubRepo(repoUrl);
  if (!parsed) return null;

  const url = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}`;
  try {
    const res = await fetch(url, { headers: { "User-Agent": "hyzen" } });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.default_branch || null;
  } catch {
    return null;
  }
}

async function gitRemoteHasBranch(repoUrl, branchName) {
  if (!branchName) return false;
  try {
    const out = await execFileAsync(
      "git",
      ["ls-remote", "--heads", repoUrl, branchName],
      { windowsHide: true }
    );
    const stdout = out?.stdout || "";
    return stdout.trim().length > 0;
  } catch {
    return false;
  }
}

async function resolveCloneBranch(repoUrl, requestedBranch) {
  if (requestedBranch) {
    const ok = await gitRemoteHasBranch(repoUrl, requestedBranch);
    if (ok) return requestedBranch;
  }
  if (await gitRemoteHasBranch(repoUrl, "main")) return "main";
  if (await gitRemoteHasBranch(repoUrl, "master")) return "master";
  const fallback = await getDefaultBranchFromGitHub(repoUrl);
  return fallback || requestedBranch || "main";
}

function isBranchNotFoundError(err) {
  const text = `${err?.message || ""}\n${err?.stderr || ""}\n${err?.stdout || ""}`.toLowerCase();
  return (
    text.includes("branch") &&
    (text.includes("not found") ||
      text.includes("couldn't find") ||
      text.includes("could not find") ||
      text.includes("remote ref") ||
      text.includes("no such remote branch"))
  );
}

function sanitizeContainerName(containerName) {
  const raw = String(containerName || "");
  const safeName = raw.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return safeName;
}

function writeDockerfile(cloneDir, content) {
  fs.writeFileSync(path.join(cloneDir, "Dockerfile"), content, "utf8");
}

function maybeAutoGenerateDockerfile(cloneDir) {
  const dockerfilePath = path.join(cloneDir, "Dockerfile");
  if (fs.existsSync(dockerfilePath)) return { generated: false, containerPort: null };

  const hasPackageJson = fs.existsSync(path.join(cloneDir, "package.json"));
  const hasRequirements = fs.existsSync(path.join(cloneDir, "requirements.txt"));
  const hasIndexHtml = fs.existsSync(path.join(cloneDir, "index.html"));

  if (hasPackageJson) {
    writeDockerfile(cloneDir, [
      "FROM node:18-alpine",
      "WORKDIR /app",
      "COPY package*.json ./",
      "RUN npm install",
      "COPY . .",
      "EXPOSE 3000",
      'CMD ["node", "index.js"]',
      "",
    ].join("\n"));
    return { generated: true, containerPort: 3000 };
  }

  if (hasRequirements) {
    writeDockerfile(cloneDir, [
      "FROM python:3.11-slim",
      "WORKDIR /app",
      "COPY requirements.txt .",
      "RUN pip install -r requirements.txt",
      "COPY . .",
      "EXPOSE 8000",
      'CMD ["python", "app.py"]',
      "",
    ].join("\n"));
    return { generated: true, containerPort: 8000 };
  }

  if (hasIndexHtml) {
    writeDockerfile(cloneDir, [
      "FROM nginx:alpine",
      "COPY . /usr/share/nginx/html",
      "EXPOSE 80",
      "",
    ].join("\n"));
    return { generated: true, containerPort: 80 };
  }

  throw new Error(
    "No Dockerfile found. Please add a Dockerfile to your repo root. See hyzen.pro/docs for examples."
  );
}

function envInputToPairs(envInput) {
  if (!envInput) return [];
  if (Array.isArray(envInput)) return envInput;
  if (typeof envInput === "object") {
    return Object.entries(envInput).map(([key, value]) => ({ key, value }));
  }
  return [];
}

function normalizeEnv(envPairs) {
  const envArr = [];
  for (const pair of envPairs) {
    const rawKey = String(pair?.key || "").trim();
    const rawValue = String(pair?.value ?? "").toString();
    if (!rawKey) continue;

    const safeKey = rawKey
      .replace(/\s+/g, "_")
      .replace(/[^A-Za-z0-9_]/g, "_")
      .toUpperCase();

    envArr.push(`${safeKey}=${rawValue}`);
  }
  return envArr;
}

function parseCpuToNanoCpus(cpu) {
  const n = Number(cpu);
  if (Number.isNaN(n)) return 500000000;
  return Math.round(n * 1e9);
}

function ramMbToBytes(ramMb) {
  const n = Number(ramMb);
  if (Number.isNaN(n)) return 512 * 1024 * 1024;
  return n * 1024 * 1024;
}

function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once("error", () => resolve(false));
    server.once("listening", () => {
      server.close(() => resolve(true));
    });
    server.listen(port, "0.0.0.0");
  });
}

async function getRandomAvailablePort(minPort = 3000, maxPort = 9000) {
  const attempts = 120;
  for (let i = 0; i < attempts; i++) {
    const port = Math.floor(Math.random() * (maxPort - minPort + 1)) + minPort;
    // eslint-disable-next-line no-await-in-loop
    const ok = await isPortAvailable(port);
    if (ok) return port;
  }
  for (let port = minPort; port <= maxPort; port++) {
    // eslint-disable-next-line no-await-in-loop
    const ok = await isPortAvailable(port);
    if (ok) return port;
  }
  throw new Error(`No available port in range ${minPort}-${maxPort}`);
}

async function detectExposedPort(docker, imageTag, fallbackPort) {
  try {
    const img = docker.getImage(imageTag);
    const info = await img.inspect();
    const exposed = info?.Config?.ExposedPorts || {};
    const keys = Object.keys(exposed);
    if (!keys.length) return fallbackPort;
    const key = keys[0];
    const port = Number(String(key).split("/")[0]);
    if (!Number.isNaN(port) && port > 0) return port;
    return fallbackPort;
  } catch {
    return fallbackPort;
  }
}

async function containerExists(docker, name) {
  const containers = await docker.listContainers({ all: true });
  const found = containers.find((c) => {
    const names = c.Names || [];
    return names.some((nm) => nm.replace(/^\//, "") === name);
  });
  return found || null;
}

async function assertImageAvailable(docker, imageName, { attempts = 5, delayMs = 2000, onLog } = {}) {
  const log = (s = "") => { try { onLog?.(s); } catch {} };
  for (let i = 0; i < attempts; i++) {
    try {
      const img = docker.getImage(imageName);
      await img.inspect();
      log(`Image verified: ${imageName}\n`);
      return true;
    } catch {
      log(`Image not ready yet (attempt ${i+1}/${attempts})...\n`);
      await new Promise(r => setTimeout(r, delayMs));
    }
  }
  throw new Error(`Image ${imageName} not found after build.`);
}

async function deployToDocker({
  repoUrl,
  branch,
  containerName,
  ramMb,
  cpuCores,
  env,
  onLog,
}) {
  const log = (s = "") => {
    try {
      onLog?.(s);
    } catch {}
  };

  const safeName = sanitizeContainerName(containerName);
  if (!safeName) {
    throw new Error("Invalid containerName");
  }

  const targetRamMb = ramMb || "512";
  const targetCpu = cpuCores || "0.5";

  let tmpDir = null;
  const docker = dockerInstance();

  invalidate();

  try {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "hyzen-"));
    const cloneDir = path.join(tmpDir, "repo");

    const usedBranch = await resolveCloneBranch(repoUrl, branch || null);
    log(`Resolved branch: ${usedBranch}\n`);

    const tryClone = async (branchToTry) => {
      if (fs.existsSync(cloneDir)) {
        fs.rmSync(cloneDir, { recursive: true, force: true });
      }
      log(`Cloning ${repoUrl} (${branchToTry})...\n`);
      await execFileAsync(
        "git",
        ["clone", "--depth", "1", "--branch", branchToTry, repoUrl, cloneDir],
        { windowsHide: true, maxBuffer: 20 * 1024 * 1024 }
      );
      log("Clone complete.\n");
      return branchToTry;
    };

    let usedBranchFinal = usedBranch;
    try {
      usedBranchFinal = await tryClone(usedBranch);
    } catch (cloneErr) {
      if (isBranchNotFoundError(cloneErr)) {
        const fallback =
          usedBranch === "main"
            ? "master"
            : usedBranch === "master"
              ? "main"
              : null;
        if (fallback) {
          log(`Branch not found. Retrying with "${fallback}"...\n`);
          usedBranchFinal = await tryClone(fallback);
        } else {
          const alt = await resolveCloneBranch(repoUrl, null);
          if (alt && alt !== usedBranch) {
            log(`Retrying with "${alt}" from detection...\n`);
            usedBranchFinal = await tryClone(alt);
          } else {
            throw cloneErr;
          }
        }
      } else {
        throw cloneErr;
      }
    }

    const autoDocker = maybeAutoGenerateDockerfile(cloneDir);

    const imageTag = `hyzen/${safeName}:latest`;
    log(`Building Docker image ${imageTag}...\n`);
    log(`Build will output image: ${imageTag}\n`);

    await new Promise((resolve, reject) => {
      const buildProcess = require('child_process').spawn(
        'docker', ['build', '-t', imageTag, cloneDir],
        { stdio: ['ignore', 'pipe', 'pipe'] }
      );
      buildProcess.stdout.on('data', (data) => log(data.toString()));
      buildProcess.stderr.on('data', (data) => log(data.toString()));
      buildProcess.on('close', (code) => {
        if (code === 0) resolve();
        else reject(new Error(`Docker build failed with exit code ${code}`));
      });
    });

    log("Build complete.\n");

    const existing = await containerExists(docker, safeName);
    if (existing?.Id) {
      log(`Removing existing container "${safeName}"...\n`);
      const old = docker.getContainer(existing.Id);
      try {
        await old.stop({ t: 10 });
      } catch {}
      try {
        await old.remove({ force: true });
      } catch {}
    }

    const hostPort = await getRandomAvailablePort(3000, 9000);
    const url = `http://localhost:${hostPort}`;

    const exposedPortFallback = autoDocker?.containerPort || 3000;
    const containerPort = await detectExposedPort(docker, imageTag, exposedPortFallback);

    const envPairs = envInputToPairs(env);
    const envArr = normalizeEnv(envPairs);

    const containerPortKey = `${containerPort}/tcp`;

    const hostConfig = {
      NanoCPUs: parseCpuToNanoCpus(targetCpu),
      Memory: ramMbToBytes(targetRamMb),
      PortBindings: {
        [containerPortKey]: [{ HostPort: String(hostPort) }],
      },
    };

    log(`Starting container "${safeName}"...\n`);
    log(`Running with image tag: ${imageTag}\n`);

    let container;
    try {
      container = await docker.createContainer({
        name: safeName,
        Image: imageTag,
        HostConfig: hostConfig,
        ExposedPorts: { [containerPortKey]: {} },
        ...(envArr.length ? { Env: envArr } : {}),
      });
    } catch (createErr) {
      // eslint-disable-next-line no-console
      console.error("createContainer failed", {
        safeName,
        imageTag,
        containerPort,
        hostPort,
        error: createErr?.message || String(createErr),
      });
      throw createErr;
    }

    await container.start();

    log(`Service URL: ${url}\n`);
    log(`${url}\n`);
    log("Deployment complete.\n");

    return {
      safeName,
      imageTag,
      usedBranch: usedBranchFinal,
      url,
      hostPort,
      containerPort,
      ram: targetRamMb,
      cpu: targetCpu,
      containerId: container.id || null,
    };
  } finally {
    if (tmpDir) {
      try {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      } catch {}
    }
  }
}

module.exports = {
  deployToDocker,
};

