const express = require("express");
const Docker = require("dockerode");
const path = require("path");
const os = require("os");
const fs = require("fs");
const util = require("util");
const net = require("net");
const { execFile } = require("child_process");

const router = express.Router();
const { getSettings, getPool } = require("../db");
const { invalidate } = require("../containersCache");

const execFileAsync = util.promisify(execFile);

// WITH:
function dockerFromSettings() {
  return new Docker({ socketPath: process.env.DOCKER_SOCKET || "/var/run/docker.sock" });
}

function parseCpuToNanoCpus(cpu) {
  const n = Number(cpu);
  if (Number.isNaN(n)) return 500000000;
  // Docker uses NanoCPUs where 1.0 core == 1e9.
  return Math.round(n * 1e9);
}

function ramMbToBytes(ramMb) {
  const n = Number(ramMb);
  if (Number.isNaN(n)) return 512 * 1024 * 1024;
  return n * 1024 * 1024;
}

async function containerExists(docker, name) {
  const containers = await docker.listContainers({ all: true });
  const found = containers.find((c) => {
    const names = c.Names || [];
    return names.some((nm) => nm.replace(/^\//, "") === name);
  });
  return found || null;
}

function sanitizeContainerName(containerName) {
  const raw = String(containerName || "");
  const safeName = raw.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return safeName;
}

function isBranchNotFoundError(err) {
  const text = `${err?.message || ""}\n${err?.stderr || ""}\n${err?.stdout || ""}`.toLowerCase();
  return (
    text.includes("branch") &&
    (text.includes("not found") ||
      text.includes("couldn't find") ||
      text.includes("could not find") ||
      text.includes("remote ref") ||
      text.includes("no such remote branch"))
  );
}

function parseGitHubRepo(repoUrl) {
  let runOk = false;
  try {
    // Example: https://github.com/owner/repo.git
    const m = String(repoUrl).match(/^https?:\/\/github\.com\/([^/]+)\/([^/]+?)(?:\.git)?$/i);
    if (!m) return null;
    return { owner: m[1], repo: m[2] };
  } catch {
    return null;
  }
}

async function getDefaultBranchFromGitHub(repoUrl) {
  const parsed = parseGitHubRepo(repoUrl);
  if (!parsed) return null;

  const url = `https://api.github.com/repos/${parsed.owner}/${parsed.repo}`;
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "hyzen" },
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.default_branch || null;
  } catch {
    return null;
  }
}

async function gitRemoteHasBranch(repoUrl, branchName) {
  if (!branchName) return false;
  try {
    const out = await execFileAsync(
      "git",
      ["ls-remote", "--heads", repoUrl, branchName],
      { windowsHide: true }
    );
    const stdout = out?.stdout || "";
    return stdout.trim().length > 0;
  } catch {
    return false;
  }
}

async function resolveCloneBranch(repoUrl, requestedBranch) {
  // If requested branch exists, use it.
  if (requestedBranch) {
    const ok = await gitRemoteHasBranch(repoUrl, requestedBranch);
    if (ok) return requestedBranch;
  }

  // Otherwise: check main → master → GitHub default branch.
  if (await gitRemoteHasBranch(repoUrl, "main")) return "main";
  if (await gitRemoteHasBranch(repoUrl, "master")) return "master";
  const fallback = await getDefaultBranchFromGitHub(repoUrl);
  return fallback || requestedBranch || "main";
}

function writeDockerfile(cloneDir, content) {
  fs.writeFileSync(path.join(cloneDir, "Dockerfile"), content, "utf8");
}

function maybeAutoGenerateDockerfile(cloneDir) {
  const dockerfilePath = path.join(cloneDir, "Dockerfile");
  if (fs.existsSync(dockerfilePath)) return { generated: false, containerPort: null };

  const hasPackageJson = fs.existsSync(path.join(cloneDir, "package.json"));
  const hasRequirements = fs.existsSync(path.join(cloneDir, "requirements.txt"));
  const hasIndexHtml = fs.existsSync(path.join(cloneDir, "index.html"));

  if (hasPackageJson) {
    writeDockerfile(cloneDir, [
      "FROM node:18-alpine",
      "WORKDIR /app",
      "COPY package*.json ./",
      "RUN npm install",
      "COPY . .",
      "EXPOSE 3000",
      'CMD ["node", "index.js"]',
      "",
    ].join("\n"));
    return { generated: true, containerPort: 3000 };
  }

  if (hasRequirements) {
    writeDockerfile(cloneDir, [
      "FROM python:3.11-slim",
      "WORKDIR /app",
      "COPY requirements.txt .",
      "RUN pip install -r requirements.txt",
      "COPY . .",
      "EXPOSE 8000",
      'CMD ["python", "app.py"]',
      "",
    ].join("\n"));
    return { generated: true, containerPort: 8000 };
  }

  if (hasIndexHtml) {
    writeDockerfile(cloneDir, [
      "FROM nginx:alpine",
      "COPY . /usr/share/nginx/html",
      "EXPOSE 80",
      "",
    ].join("\n"));
    return { generated: true, containerPort: 80 };
  }

  throw new Error(
    "No Dockerfile found. Please add a Dockerfile to your repo root. See hyzen.pro/docs for examples."
  );
}

function envInputToPairs(envInput) {
  if (!envInput) return [];
  if (Array.isArray(envInput)) return envInput;
  if (typeof envInput === "object") {
    return Object.entries(envInput).map(([key, value]) => ({ key, value }));
  }
  return [];
}

function normalizeEnv(envPairs) {
  const envArr = [];
  for (const pair of envPairs) {
    const rawKey = String(pair?.key || "").trim();
    const rawValue = String(pair?.value ?? "").toString();
    if (!rawKey) continue;

    // Docker env keys typically want [A-Z0-9_]. We'll coerce minimally.
    const safeKey = rawKey
      .replace(/\s+/g, "_")
      .replace(/[^A-Za-z0-9_]/g, "_")
      .toUpperCase();

    envArr.push(`${safeKey}=${rawValue}`);
  }
  return envArr;
}

function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once("error", () => {
      resolve(false);
    });
    server.once("listening", () => {
      server.close(() => resolve(true));
    });
    server.listen(port, "0.0.0.0");
  });
}

async function getRandomAvailablePort(minPort = 3000, maxPort = 9000) {
  const attempts = 120;
  for (let i = 0; i < attempts; i++) {
    const port = Math.floor(Math.random() * (maxPort - minPort + 1)) + minPort;
    // eslint-disable-next-line no-await-in-loop
    const ok = await isPortAvailable(port);
    if (ok) return port;
  }
  // Fallback: sequential scan (guaranteed to finish).
  for (let port = minPort; port <= maxPort; port++) {
    // eslint-disable-next-line no-await-in-loop
    const ok = await isPortAvailable(port);
    if (ok) return port;
  }
  throw new Error(`No available port in range ${minPort}-${maxPort}`);
}

async function detectExposedPort(docker, imageTag, fallbackPort) {
  try {
    const img = docker.getImage(imageTag);
    const info = await img.inspect();
    const exposed = info?.Config?.ExposedPorts || {};
    const keys = Object.keys(exposed);
    if (!keys.length) return fallbackPort;
    const key = keys[0]; // e.g. "3000/tcp"
    const port = Number(String(key).split("/")[0]);
    if (!Number.isNaN(port) && port > 0) return port;
    return fallbackPort;
  } catch {
    return fallbackPort;
  }
}

async function assertImageAvailable(docker, imageName, { attempts = 3, delayMs = 1000, onLog } = {}) {
  let lastLen = 0;
  const log = (s = "") => {
    try {
      onLog?.(s);
    } catch {}
  };

  for (let i = 0; i < attempts; i++) {
    try {
      const images = await docker.listImages({ filters: { reference: [imageName] } });
      lastLen = images?.length || 0;
      if (lastLen > 0) return images;
    } catch (e) {
      log(`Image check failed (attempt ${i + 1}): ${e?.message || String(e)}\n`);
    }
    log(`Image not visible yet (attempt ${i + 1}/${attempts}). Waiting...\n`);
    // eslint-disable-next-line no-await-in-loop
    await new Promise((r) => setTimeout(r, delayMs));
  }

  try {
    // Sanity-check: if image is runnable, but listImages reference filter doesn't match,
    // we can still proceed. Command exits immediately.
    await docker.run(
      imageName,
      ["sh", "-c", "true"],
      null,
      { HostConfig: { AutoRemove: true } },
      {}
    );
    runOk = true;
    log(`docker.run sanity check succeeded for ${imageName}.\n`);
  } catch (e) {
    log(`docker.run sanity check failed: ${e?.message || String(e)}\n`);
  }

  if (runOk) return;

  throw new Error(
    `Image ${imageName} was built but not found. Docker TCP context mismatch or image indexing delay. (Matches: ${lastLen})`
  );
}

router.post("/", async (req, res) => {
  // Stream deployment output as plain text.
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Cache-Control", "no-cache, no-transform");
  res.setHeader("Connection", "keep-alive");

  const {
    repoUrl,
    branch,
    containerName,
    ramMb,
    cpuCores,
    ram,
    cpu,
    env,
  } = req.body || {};

  if (!repoUrl || !containerName) {
    res.status(400).end("Missing repoUrl or containerName");
    return;
  }

  const safeName = sanitizeContainerName(containerName);
  if (!safeName) {
    res.status(400).end("Invalid containerName");
    return;
  }

  const targetRamMb = ramMb || ram || "512";
  const targetCpu = cpuCores || cpu || "0.5";
  const requestedBranch = branch || null;

  let tmpDir = null;
  try {
    const settings = await getSettings().catch(() => null);
    const docker = dockerFromSettings(settings);

    // Clone
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "hyzen-"));
    const cloneDir = path.join(tmpDir, "repo");

    invalidate();

    let usedBranch = await resolveCloneBranch(repoUrl, requestedBranch);
    res.write(`Resolved branch: ${usedBranch}\n`);

    const tryClone = async (branchToTry) => {
      if (fs.existsSync(cloneDir)) {
        fs.rmSync(cloneDir, { recursive: true, force: true });
      }
      res.write(`Cloning ${repoUrl} (${branchToTry})...\n`);
      await execFileAsync(
        "git",
        ["clone", "--depth", "1", "--branch", branchToTry, repoUrl, cloneDir],
        {
          windowsHide: true,
          maxBuffer: 20 * 1024 * 1024,
        }
      );
      res.write(`Clone complete.\n`);
    };

    try {
      await tryClone(usedBranch);
    } catch (cloneErr) {
      if (isBranchNotFoundError(cloneErr)) {
        const fallback =
          usedBranch === "main" ? "master" : usedBranch === "master" ? "main" : null;
        if (fallback) {
          res.write(`Branch not found. Retrying with "${fallback}"...\n`);
          usedBranch = fallback;
          await tryClone(usedBranch);
        } else {
          const alt = await resolveCloneBranch(repoUrl, null);
          if (alt && alt !== usedBranch) {
            res.write(`Retrying with "${alt}" from detection...\n`);
            usedBranch = alt;
            await tryClone(usedBranch);
          } else {
            throw cloneErr;
          }
        }
      } else {
        throw cloneErr;
      }
    }

    // Dockerfile auto-generation (only if missing).
    const autoDocker = maybeAutoGenerateDockerfile(cloneDir);

    // Build
    const imageTag = `hyzen/${safeName}:latest`;
    res.write(`Building Docker image ${imageTag}...\n`);
    res.write(`Build will output image: ${imageTag}\n`);

    await new Promise((resolve, reject) => {
      const buildProcess = require('child_process').spawn(
        'docker', ['build', '-t', imageTag, cloneDir],
        { stdio: ['ignore', 'pipe', 'pipe'] }
      );
      buildProcess.stdout.on('data', (data) => res.write(data.toString()));
      buildProcess.stderr.on('data', (data) => res.write(data.toString()));
      buildProcess.on('close', (code) => {
        if (code === 0) resolve();
        else reject(new Error(`Docker build failed with exit code ${code}`));
      });
    });
    res.write(`Build complete.\n`);

    // Stop/remove existing container (use safeName).
    const existing = await containerExists(docker, safeName);
    if (existing?.Id) {
      res.write(`Removing existing container "${safeName}"...\n`);
      const old = docker.getContainer(existing.Id);
      try {
        await old.stop({ t: 10 });
      } catch {}
      try {
        await old.remove({ force: true });
      } catch {}
    }

    // Choose ports + env
    const hostPort = await getRandomAvailablePort(3000, 9000);
    const url = `http://localhost:${hostPort}`;

    const exposedPortFallback = autoDocker?.containerPort || 3000;
    const containerPort = await detectExposedPort(docker, imageTag, exposedPortFallback);

    const envPairs = envInputToPairs(env);
    const envArr = normalizeEnv(envPairs);

    const containerPortKey = `${containerPort}/tcp`;

    // Create + run with limits + port mapping.
    const hostConfig = {
      NanoCPUs: parseCpuToNanoCpus(targetCpu),
      Memory: ramMbToBytes(targetRamMb),
      PortBindings: {
        [containerPortKey]: [{ HostPort: String(hostPort) }],
      },
    };

    res.write(`Starting container "${safeName}"...\n`);
    res.write(`Running with image tag: ${imageTag}\n`);

    let container;
    try {
      container = await docker.createContainer({
        name: safeName,
        Image: imageTag,
        HostConfig: hostConfig,
        ExposedPorts: {
          [containerPortKey]: {},
        },
        ...(envArr.length ? { Env: envArr } : {}),
      });
    } catch (createErr) {
      // eslint-disable-next-line no-console
      console.error("createContainer failed", {
        safeName,
        imageTag,
        containerPort,
        hostPort,
        error: createErr?.message || String(createErr),
      });
      res.write(`\ncreateContainer failed: ${createErr?.message || String(createErr)}\n`);
      throw createErr;
    }

    try {
      await container.start();
    } catch (startErr) {
      // eslint-disable-next-line no-console
      console.error("container.start failed", {
        safeName,
        imageTag,
        error: startErr?.message || String(startErr),
      });
      res.write(`\ncontainer.start failed: ${startErr?.message || String(startErr)}\n`);
      throw startErr;
    }

    res.write(`Service URL: ${url}\n`);
    res.write(`${url}\n`);
    res.write(`Deployment complete.\n`);

    // Save URL to DB (best effort).
    try {
      const pool = getPool();
      await pool.query(
        `
          INSERT INTO hyzen_deployments
            (repo_url, branch, container_name, ram_mb, cpu_cores, status, output, url)
          VALUES
            ($1, $2, $3, $4, $5, $6, $7, $8);
        `,
        [
          repoUrl,
          usedBranch,
          safeName,
          Number(targetRamMb),
          Number(targetCpu),
          "running",
          "deployed",
          url,
        ]
      );
    } catch {}

    res.end();
  } catch (err) {
    try {
      res.write(`\nDeployment failed: ${err?.message || String(err)}\n`);
    } catch {}
    try {
      res.end();
    } catch {}
  } finally {
    if (tmpDir) {
      try {
        fs.rmSync(tmpDir, { recursive: true, force: true });
      } catch {}
    }
  }
});

module.exports = router;

